export const GET_ERRORS_SIGNIN = "GET_ERRORS_SIGNIN";
export const GET_ERRORS_SIGNUP = "GET_ERRORS_SIGNUP";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_OFFICES = "GET_OFFICES";
export const GET_OFFICES_ERROR = "GET_OFFICES_ERROR";
export const GET_COMPANYID_OFFICEID = "GET_COMPANYID_OFFICEID";
