export const GET_VEHICLE_TYPES = "GET_VEHICLE_TYPES";
export const GET_VEHICLE_TYPES_ERRORS = "GET_VEHICLE_TYPES_ERRORS";
export const GET_VEHICLE_CATEGORIES = "GET_VEHICLE_CATEGORIES";
export const GET_VEHICLE_CATEGORIES_ERRORS = "GET_VEHICLE_CATEGORIES_ERRORS";
export const GET_VEHICLE_OPTIONS = "GET_VEHICLE_OPTIONS";
export const GET_VEHICLE_OPTIONS_ERRORS = "GET_VEHICLE_OPTIONS_ERRORS";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const GET_ERROR_ADD_VEHICLE = "GET_ERROR_ADD_VEHICLE";
